# Generated by Django 5.0.7 on 2025-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='last_resend_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginotp',
            name='resend_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
