# Generated by Django 5.2.7 on 2025-10-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('users', '0002_loginotp_last_resend_at_loginotp_resend_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='colleges.college'),
        ),
    ]
