# Generated by Django 5.2.7 on 2025-10-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('users', '0003_user_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='university.university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('UNIVERSITY', 'University'), ('COLLEGE', 'College'), ('STAFF', 'Staff')], default='STAFF', max_length=50),
        ),
    ]
