# Generated by Django 5.2.7 on 2025-10-22 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_createpasswordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpasswordrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
