services:
  django:
    image: sarthakghere/checkmate_central-django:latest
    env_file:
      - .env
    volumes:
      - media_volume:/app/mediafiles
      - ./staticfiles:/app/staticfiles

  nginx:
    image: sarthakghere/checkmate_central-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /home/ubuntu/certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - ./staticfiles:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
    depends_on:
      - django

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  
  celery:
    image: sarthakghere/checkmate_central-django:latest
    container_name: celery
    command: celery -A checkmate_central worker -l info
    env_file:
      - .env
    depends_on:
      - django
      - redis

volumes:
  media_volume: