# Generated by Django 5.2.7 on 2025-10-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='College Code'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='College Name'),
        ),
    ]
