# Generated by Django 5.2.7 on 2025-10-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backups', '0001_initial'),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='colleges.college'),
        ),
    ]
