# Generated by Django 5.2.7 on 2025-10-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(upload_to='backups/temp/'),
        ),
    ]
