# Generated by Django 5.2.7 on 2025-10-11 09:37

import backups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_alter_backup_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(upload_to=backups.models.temp_backup_upload_path),
        ),
    ]
