# Generated by Django 5.2.7 on 2025-10-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_alter_backup_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
