# Generated by Django 5.2.7 on 2025-10-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
